# Colors (Matugen template)
set-option -g status-bg '#131318'
set-option -g status-fg '#e5e1e9'
set -g pane-border-style 'fg=#201f25'
set -g pane-active-border-style 'fg=#c6c0ff'
set -g mode-style 'fg=#131318,bg=#c6c0ff'

set -g status-left '#[fg=#c6c0ff]  #[fg=#e5e1e9]#S #[default]'
set -g status-right '#[fg=#47464f]%Y-%m-%d #[fg=#c6c0ff]%I:%M %p #[default]'
