# Colors (Matugen template)
set-option -g status-bg '#0e1415'
set-option -g status-fg '#dde4e3'
set -g pane-border-style 'fg=#1a2121'
set -g pane-active-border-style 'fg=#80d4d8'
set -g mode-style 'fg=#0e1415,bg=#80d4d8'

set -g status-left '#[fg=#80d4d8]  #[fg=#dde4e3]#S #[default]'
set -g status-right '#[fg=#3f4949]%Y-%m-%d #[fg=#80d4d8]%I:%M %p #[default]'
