## name: Matugen
## author: GPT
foreground               #dde4e3
background               #0e1415
selection_foreground     #dde4e3
selection_background     #3f4949
cursor                   #b1cccd
cursor_text_color        #1b3436
url_color                #80d4d8
active_tab_foreground    #dde4e3
active_tab_background    #3f4949
inactive_tab_foreground  #bec8c9
inactive_tab_background  #0e1415
active_border_color      #80d4d8
inactive_border_color    #899393
color0   #0e1415
color8   #3f4949
color1   #ffb4ab
color9   #ffb4ab
color2   #b5c7e9
color10  #b5c7e9
color3   #b1cccd
color11  #b1cccd
color4   #80d4d8
color12  #80d4d8
color5   #b5c7e9
color13  #b5c7e9
color6   #b1cccd
color14  #b1cccd
color7   #dde4e3
color15  #dde4e3
