## name: Matugen
## author: GPT
foreground               #e5e1e9
background               #131318
selection_foreground     #e5e1e9
selection_background     #47464f
cursor                   #c8c3dc
cursor_text_color        #302e41
url_color                #c6c0ff
active_tab_foreground    #e5e1e9
active_tab_background    #47464f
inactive_tab_foreground  #c8c5d0
inactive_tab_background  #131318
active_border_color      #c6c0ff
inactive_border_color    #928f99
color0   #131318
color8   #47464f
color1   #ffb4ab
color9   #ffb4ab
color2   #ebb8cf
color10  #ebb8cf
color3   #c8c3dc
color11  #c8c3dc
color4   #c6c0ff
color12  #c6c0ff
color5   #ebb8cf
color13  #ebb8cf
color6   #c8c3dc
color14  #c8c3dc
color7   #e5e1e9
color15  #e5e1e9
