# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# cyberdream theme for lazygit
gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#5f8787"  # base08 (teal accent)
      - bold
    inactiveBorderColor:
      - "#333333"  # base03 (dark gray)
    searchingActiveBorderColor:
      - "#8c7f70"  # base0A (brownish accent)
    optionsTextColor:
      - "#c1c1c1"  # base05 (primary text)
    selectedLineBgColor:
      - "#121212"  # base01 (darker background)
    cherryPickedCommitBgColor:
      - "#121212"  # base01
    cherryPickedCommitFgColor:
      - "#5f8787"  # base08
    unstagedChangesColor:
      - "#8c7f70"  # base0A
    defaultFgColor:
      - "#c1c1c1"  # base05
