gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#9ccfd8"  # foam (cyan)
      - bold
    inactiveBorderColor:
      - "#6e6a86"  # muted
    searchingActiveBorderColor:
      - "#f6c177"  # gold
    optionsTextColor:
      - "#e0def4"  # text
    selectedLineBgColor:
      - "#26233a"  # overlay
    cherryPickedCommitBgColor:
      - "#26233a"  # overlay
    cherryPickedCommitFgColor:
      - "#eb6f92"  # love
    unstagedChangesColor:
      - "#f6c177"  # gold
    defaultFgColor:
      - "#e0def4"  # text
