# Prompt symbols
[character]
success_symbol = "[❯](bold #cacb77)"  # Foam color
error_symbol = "[❯](bold #a4d0bd)"  # Love color

# Directory Path
[directory]
format            = "[$path](cyan) "
style = "bold #c9c7b6"  # Text color
read_only = " "
read_only_style = "bold #cacb77"  # Gold color
truncation_length = 4
truncate_to_repo  = true

# Git Branch
[git_branch]
symbol = " "
style = "bold #cacb77"  # Iris color

# Git Status
[git_status]
style = "bold #cacb77"  # Gold
conflicted = "⚔ "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
modified = "*"
staged = "+"
deleted = "✘"
untracked = "?"

# Disable unused modules for minimalism
[package]
disabled = true

# scan_timeout = 0
