[font]
size = 11

builtin_box_drawing = true

normal = { family = "Iosevka Term", style = "SemiBold" }
bold = { family = "Iosevka Term", style = "Bold" }
italic = { family = "Iosevka Term", style = "Italic" }
bold_italic = { family = "Iosevka Term", style = "Bold Italic" }
