# Prompt symbols
[character]
success_symbol = "[❯](bold #c6c0ff)"  # Foam color
error_symbol = "[❯](bold #ebb8cf)"  # Love color

# Directory Path
[directory]
style = "bold #c8c5d0"  # Text color
read_only = " "
read_only_style = "bold #c6c0ff"  # Gold color

# Git Branch
[git_branch]
symbol = " "
style = "bold #c6c0ff"  # Iris color

# Git Status
[git_status]
style = "bold #c6c0ff"  # Gold
conflicted = "⚔ "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
modified = "*"
staged = "+"
deleted = "✘"
untracked = "?"

# Disable unused modules for minimalism
[package]
disabled = true

scan_timeout = 0
